#!/bin/bash

EXE=$(readlink $0)
[ -z "$EXE" ] && EXE=$0
DIR=$(dirname $EXE)
EXE=osconfig.py

if [ -x "$DIR/$EXE" ]
then
    echo "Start $EXE ..."
    $DIR/$EXE
else
    echo "Error: no $EXE"
    exit 1
fi
