#ifndef __LY_INCLUDE_OSMANAGER_LYOSM_H
#define __LY_INCLUDE_OSMANAGER_LYOSM_H

#define PROGRAM_NAME "lyosm"
#define PROGRAM_VERSION "0.1"

#define DEFAULT_OSM_INSTALL_PATH "./LuoYun/"
#define DEFAULT_OSM_CONF_PATH DEFAULT_OSM_INSTALL_PATH "conf/luoyun.conf"
#define DEFAULT_OSM_KEY_PATH DEFAULT_OSM_INSTALL_PATH "conf/luoyun.key"
#define DEFAULT_OSM_LOG_PATH DEFAULT_OSM_INSTALL_PATH "log/luoyun.log"

#define LY_OSM_KEEPALIVE_INTVL 10
#define LY_OSM_KEEPALIVE_PROBES 3

#endif
