#ifndef __LY_INCLUDE_OSMANAGER_LYOSM_H
#define __LY_INCLUDE_OSMANAGER_LYOSM_H

#define PROGRAM_NAME "lyosm"
#define PROGRAM_VERSION "0.2"

#define DEFAULT_OSM_INSTALL_DIR "/LuoYun/"
#define DEFAULT_OSM_CONF_PATH DEFAULT_OSM_INSTALL_DIR "conf/luoyun.conf"
#define DEFAULT_OSM_KEY_PATH DEFAULT_OSM_INSTALL_DIR "conf/luoyun.key"
#define DEFAULT_OSM_LOG_PATH DEFAULT_OSM_INSTALL_DIR "log/luoyun.log"
#define DEFAULT_OSM_SCRIPTS_DIR DEFAULT_OSM_INSTALL_DIR "scripts"

#define LY_OSM_KEEPALIVE_INTVL 10
#define LY_OSM_KEEPALIVE_PROBES 3

#define LY_OSM_STATUS_CHECK_INTVL 5

#endif
