#!/bin/bash

EXE=$(readlink $0)
[ -z "$EXE" ] && EXE=$0
DIR=$(dirname $EXE)
EXE=shellinaboxd

if [ -x "$DIR/$EXE" ]
then
    echo "Start $EXE ..."
    $DIR/$EXE -t -b -p 8001 -s /:SSH
else
    echo "Error: no $EXE"
    exit 1
fi
