#!/bin/sh

EXE=$(readlink $0)
[ -z "$EXE" ] && EXE=$0
DIR=$(dirname $EXE)
EXE=lyweb.py

if [ -x "$DIR/$EXE" ]
then
    echo "Start $EXE ..."
    $DIR/$EXE 8080 &
else
    echo "Error: no $EXE"
    exit 1
fi
